### ISSUE TITLE
System.IO.IOException: Unknown frame descriptor

### ISSUE THREAD

**Issue by Namsku** [Ekey/REE.PAK.Tool#38]
Hello i have this awkward but with RE2 Remake Non RT 

- **Project:** RE2_PC_Release (Non-RT)
- **File to unpack:** re_chunk_000.pak

...
[UNPACKING]: natives/x64/streaming/sectionroot/character/player/pl5300/pl5300/pl5300_03/pl5300_03_body_albm.tex.10
[UNPACKING]: natives/x64/streaming/sectionroot/character/player/pl5300/pl5300/pl5300_03/pl5300_03_body_nrmr.tex.10
[UNPACKING]: natives/x64/streaming/sectionroot/character/player/pl5300/pl5350/pl5350_02/pl5350_02_face_albm.tex.10
[UNPACKING]: natives/x64/streaming/sectionroot/character/player/pl5300/pl5350/pl5350_02/pl5350_02_face_nrmr.tex.10
[UNPACKING]: natives/x64/streaming/sectionroot/character/player/pl5400/pl5400/pl5400_body02_alp1.tex.10

Unhandled Exception: System.IO.IOException: Unknown frame descriptor
   at Zstandard.Net.ZstandardInterop.ThrowIfError(UIntPtr code)
   at Zstandard.Net.ZstandardStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at REE.Unpacker.ZSTD.iDecompress(Byte[] lpSrcBuffer) in E:\Projects\Mods\Biorand\re2rr\REE.Unpacker\FileSystem\Compression\ZSTD.cs:line 19
   at REE.Unpacker.PakUnpack.iDoIt(String m_PakFile, String m_DstFolder) in E:\Projects\Mods\Biorand\re2rr\REE.Unpacker\FileSystem\Package\PakUnpack.cs:line 138
   at REE.Unpacker.Program.Main(String[] args) in E:\Projects\Mods\Biorand\re2rr\REE.Unpacker\Program.cs:line 61
`

Kind Regards

**Comment by Ekey** [comment]
Hi, fixed :)

**Comment by Namsku** [comment]
I think i got it, it's likely due to a fluffy mod conflict by mistake
